### ISSUE TITLE
Fehlende html tags

### ISSUE THREAD

**Issue by MrTroble** [codingbytimo/codingbytimo.github.io#1]
https://github.com/codingbytimo/codingbytimo.github.io/blob/4f4f2c764933ac4991de81f92eed39c3eb954aca/index.html#L2

Ich rate dir zu nem html linter

**Comment by MrTroble** [comment]
```
The <html> tag represents the root of an HTML document.

The <html> tag is the container for all other HTML elements (except for the <!DOCTYPE> tag).

Note: You should always include the lang attribute inside the <html> tag, to declare the language of the Web page. This is meant to assist search engines and browsers
```
https://www.w3schools.com/TAgs/tag_html.asp

**Comment by codingbytimo** [comment]
Thx für die Info, falls noch was ist sag's einfach, hilft mir beim lernen 👍

**Comment by MrTroble** [comment]
Gerne gerne! Super das du das so annimmst 👍
